apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: {{ .Release.Namespace }}
  labels:
    app: kibana
spec:
  replicas: {{ .Values.kibanaReplicaCount }}
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
      - name: kibana
        image: "{{ .Values.kibanaImage }}:{{ .Values.kibanaImageTag }}"
        env:
          - name: ELASTICSEARCH_URL
            value: http://elasticsearch:9200
        ports:
        - containerPort: 5601
---
kind: Service
apiVersion: v1
metadata:
  name: kibana
  namespace: {{ .Release.Namespace }}
  labels:
    app: kibana
spec:
  selector:
    app: kibana
  ports:
    - port: 5601
      name: kibana-web