kind: Service
apiVersion: v1
metadata:
  name: elasticsearch
  namespace: {{ .Release.Namespace }}
  labels:
    app: elasticsearch
spec:
  selector:
    app: elasticsearch-node
  # By default service type would be ClusterIP but the value of ClusterIP itself would be none to set headless service
  clusterIP: None
  ports:
    - port: 9200
      name: client-node
    - port: 9300
      name: inter-node